### ISSUE TITLE
2FA via imap

### ISSUE THREAD

**Issue by lennyzaman** [jasonxh/arlo-mqtt#10]
Hi,

Would it be possible to implement the 2FA via IMAP functionality from the **pyaarlo** package in your docker app?

Best regards
Lenny

**Comment by jasonxh** [comment]
@lennyzaman I've pushed a docker build adding support for extra Pyaarlo options. In theory, you should be able to use it to add 2FA support with something like this:
```
docker run --rm -it jasonxh/arlo-mqtt:pyaarlo-extras -- --arlo-extras-json '{"tfa_source": "imap", "tfa_type": "email", "tfa_host": "imap.host.com", "tfa_username": "your-user-name", "tfa_password": "your-imap-password"}' <OTHER_OPTIONS>
```

I haven't been able to test it myself. Please comment if it works.

**Comment by lennyzaman** [comment]
Hi,
So far so good!
I'll keep it running and let you know if I run into issues, thank you very much!

**Comment by jasonxh** [comment]
That is great to hear. You are welcome!
